---
- name: 'restart-docker-nginx'
  sudo: true
  docker:
    image: "nginx:{{ nginx_docker_tag }}"
    name: "{{ nginx_container_name }}"
    volumes: '{{ nginx_exposed_volumes }}'
    ports: '{{ nginx_published_ports }}'
    expose: '{{ nginx_exposed_ports }}'
    state: 'stopped'
    restart_policy: 'always'
    log_driver: 'syslog'
    log_opt:
      syslog-tag: "{{ nginx_container_name }}"
  notify: 'start-docker-nginx'

- name: 'start-docker-nginx'
  sudo: true
  docker:
    image: "nginx:{{ nginx_docker_tag }}"
    name: "{{ nginx_container_name }}"
    volumes: '{{ nginx_exposed_volumes }}'
    ports: '{{ nginx_published_ports }}'
    expose: '{{ nginx_exposed_ports }}'
    state: 'started'
    restart_policy: 'always'
    log_driver: 'syslog'
    log_opt:
      syslog-tag: "{{ nginx_container_name }}"
